apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: harsh3305/hrv-mart-frontend
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: backend-url
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030
