name: Build Pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
env:
  APPWRITE_ENDPOINT: http://localhost/v1
  APPWRITE_PROJECT_ID: PROJECT_ID

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - run: npm i
      - run: npm run build
